export const SELECT_VIDEO_ACTION = 'SELECT_VIDEO';
export const FETCH_VIDEO_ACTION = 'FETCH_VIDEO';
export const SELECT_TEAM_ACTION = 'SELECT_TEAM';
export const SELECT_GAMEDAY_ACTION = 'SELECT_GAMEDAY';
